# Generated by Django 3.2.8 on 2022-02-20 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinician',
            fields=[
                ('username', models.CharField(default='', max_length=128, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(default='', max_length=128, null=True)),
                ('last_name', models.CharField(default='', max_length=128, null=True)),
                ('password', models.CharField(default='', max_length=256, null=True)),
                ('email', models.EmailField(default='', max_length=254, null=True, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='female', max_length=32)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('department', models.CharField(choices=[('1', 'Radiology Department'), ('4', 'Inpatient Service'), ('5', 'Other Department'), ('3', 'Outpatient Department'), ('2', 'Medical Record Department')], default='female', max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('username', models.CharField(default='', max_length=128, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(default='', max_length=128, null=True)),
                ('last_name', models.CharField(default='', max_length=128, null=True)),
                ('password', models.CharField(default='', max_length=256, null=True)),
                ('email', models.EmailField(default='', max_length=254, null=True, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='female', max_length=32)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('MyClinician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.clinician')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
