# Generated by Django 3.2.12 on 2022-02-17 05:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220217_0451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='patients',
        ),
        migrations.AddField(
            model_name='clinician',
            name='department',
            field=models.CharField(choices=[('1', 'Radiology Department'), ('2', 'Medical Record Department'), ('3', 'Outpatient Department'), ('4', 'Inpatient Service'), ('5', 'Other Department')], default=datetime.datetime(2022, 2, 17, 5, 1, 52, 984849, tzinfo=utc), max_length=1),
            preserve_default=False,
        ),
    ]
