# Generated by Django 3.2.12 on 2022-02-17 05:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220217_0501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='clinicians',
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2022, 2, 17, 5, 10, 32, 614899, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
