# Generated by Django 3.2.12 on 2022-02-17 05:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_unqiue_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinician',
            name='clinician_no',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='unqiue_number',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36),
        ),
    ]
