# Generated by Django 3.2.8 on 2022-02-20 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Threshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Threshold', models.IntegerField()),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('belongPatient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='', max_length=128)),
                ('score', models.FloatField()),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('TestBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Thresholds', models.IntegerField()),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('alterBy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='functions.measurement')),
                ('belongPatient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.patient')),
            ],
        ),
    ]
