# Generated by Django 3.2.8 on 2022-02-20 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['-c_time']},
        ),
        migrations.AlterModelOptions(
            name='measurement',
            options={'ordering': ['-c_time']},
        ),
    ]
