# Generated by Django 3.2.8 on 2022-02-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0002_auto_20220220_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threshold',
            name='Threshold',
        ),
        migrations.AddField(
            model_name='threshold',
            name='ThresholdScoreMax',
            field=models.FloatField(default=140.0),
        ),
        migrations.AddField(
            model_name='threshold',
            name='ThresholdScoreMin',
            field=models.FloatField(default=70.0),
        ),
        migrations.AddField(
            model_name='threshold',
            name='type',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='alert',
            name='Thresholds',
            field=models.FloatField(),
        ),
    ]
