# Generated by Django 3.2.8 on 2022-02-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0003_auto_20220220_1522'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='threshold',
            options={'ordering': ['-c_time']},
        ),
        migrations.AddField(
            model_name='measurement',
            name='altered',
            field=models.BinaryField(default=False),
        ),
    ]
