# Generated by Django 3.2.8 on 2022-02-20 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0004_auto_20220220_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='altered',
        ),
        migrations.AddField(
            model_name='measurement',
            name='alerted',
            field=models.BooleanField(default=False),
        ),
    ]
